export default {
    REPLACE_USER_INFO: 'REPLACE_USER_INFO',
    CLEAR_USER_INFO: 'CLEAR_USER_INFO' ,
    REPLACE_INSURANCE_INFO: 'REPLACE_INSURANCE_INFO',
    CLEAR_INSURANCE_INFO: 'CLEAR_INSURANCE_INFO' 
}
